version: "2"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tsydzik
      MYSQL_USER: tsydzik
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"